file:
  directory: /home/download/ca2sa/image

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://192.168.0.144/db_even_first_4
    username: even_first_4
    password: cell