const:
  default-page-size: 20
file:
  directory: D:/LJY/KA2SA/image

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: KA2SA
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/ka2sa
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
  cache:
    disabled: true