const:
  default-page-size: 20
  auth-code-length: 6

file:
  directory: D:\pjh\CA2SA\image

mybatis:
  mapper-locations: mappers.menu/**/*.xml

spring:
  application:
    name: CA2SA
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/ca2sa
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: 0ca2sa0@gmail.com
    password: wotrvbcpartvbbmk
    properties:
      mail:
        smtp:
          auth: true  # SMTP 인증 사용
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
  cache:
    disabled: true